services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/postgres/migration:/app/migration
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - HTTP_SERVER_ADDRESS=${HTTP_SERVER_ADDRESS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SOURCE=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - MIGRATION_URL=file://migration
      - TOKEN_SYMMETRIC_KEY=${TOKEN_SYMMETRIC_KEY}
      - ACCESS_TOKEN_DURATION=${ACCESS_TOKEN_DURATION}
      - REFRESH_TOKEN_DURATION=${REFRESH_TOKEN_DURATION}

volumes:
  data-volume:

