apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-parking-lot-parkings-service
spec:
  selector:
    matchLabels:
      app: go-parking-lot-parkings-service
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-parking-lot-parkings-service
    spec:
      containers:
        - name: go-parking-lot-parkings-service
          image: "go-parking-lot-parkings-service"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: parkings-config
---
apiVersion: v1
kind: Service
metadata:
  name: go-parking-lot-parkings-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: go-parking-lot-parkings-service
