services:
  parkings-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - HTTP_SERVER_ADDRESS=${HTTP_SERVER_ADDRESS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SOURCE=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - MIGRATION_URL=${MIGRATION_URL}
      - TOKEN_SYMMETRIC_KEY=${TOKEN_SYMMETRIC_KEY}
      - ACCESS_TOKEN_DURATION=${ACCESS_TOKEN_DURATION}
      - REFRESH_TOKEN_DURATION=${REFRESH_TOKEN_DURATION}

  rabbitmq:
    image: "rabbitmq:4.0-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
